### PR TITLE
Remove layers

### PR DESCRIPTION
**Pull request by jorge07**
* Removed phpunit I favour of the one in your `vendor/bin`
* Removed travis.yml[EDITED]**Added real travis tests**[\EDITED] 
* Moved to `ADD` instead `COPY` to reduce drastically the number of layers and restructured the filesystem in `rootfs` and `devfs`.

### CODE REVIEW

**Comment by jorge07** [comment]
Ping @ismael-benitez

**Comment by 1ma** [comment]
Why did you remove the Travis integration?

**Comment by jorge07** [comment]
Not using it, not useful at all, thinking on alternatives.

**Comment by 1ma** [comment]
Well, if you think about it Docker Hub is already a CI service for Docker images.

**Comment by jorge07** [comment]
Not, it isn't. I'm currently thinking about tests the configuration, xdebug integration and a performance test. But I wanna keep the automated buildings in docker Hub. I'll moved into tag instead push soon.

**Comment by 1ma** [comment]
Ah, I figured you only wanted to test that the images built fine.

I managed to do something similarish to that with Scrutinizer: https://github.com/1ma/RedisSessionHandler/blob/master/.scrutinizer.yml

Under `override:` you can execute arbitrary `docker` and `docker-compose` commands (in fact `composer test` [does just that](https://github.com/1ma/RedisSessionHandler/blob/master/composer.json#L28)). You must first figure out how your testing environment will be and how you'll interact with it, though.

**Comment by 1ma** [comment]
Staying on topic the PR looks fine, I just don't grok where these rootfs and devfs come from.

**Comment by jorge07** [comment]
Rootfs it's the filesystem of the base Dockerfile. Devfs it's the filesystem of the development environment. 

I do it like that to avoid have multiple COPY instructions, which means a layer per instruction. 

I'm second hand, I found so much easier replicate the fs structure to edit the files I need inside the container. 

So, basically the original filesystem it's the alpine one. Extended by Rootfs and in the development image extended by Devfs. 

So that the reason behind.

**Pull request merged**
