### PR TITLE
PHP 7.4

### LINKED ISSUE #61: Bump images
Hello, 

Is it possible to upgrade images with new PHP version? PHP Alpine was updated yesterday. 7.2 and 7.3 branches

Thanks @jorge07 👊

### PR DESCRIPTION
**Pull request by Lutacon**
Fix #61

### CODE REVIEW

**Comment by jorge07** [comment]
Seems there's a BC in the 7.4 memory output. Will look

**Comment by jorge07** [comment]
need backport? https://github.com/jorge07/alpine-php/pull/62

**Comment by Lutacon** [comment]
I will fix it later but i think the problem is the file `50-settings.ini`

**Comment by Lutacon** [comment]
Fixed the issue with the name of the file and backported the #62

**Comment by jorge07** [comment]
Thanks!

**Pull request merged**
