### PR TITLE
PHP 8.0

### PR DESCRIPTION
**Pull request by cv65kr**

### CODE REVIEW

**Comment by jorge07** [comment]
https://github.com/jorge07/alpine-php/blob/master/.github/workflows/pr.yaml#L13 and release needs 8.0 in order to test and release. The rest lgym

**Comment by cv65kr** [comment]
Good point, updated.

**Comment by jorge07** [comment]
Some version are release candidate but we can be updating this once the upstream cast repo release the stables.

**Comment by jorge07** [comment]
Ready to merge

**Comment by jorge07** [comment]
Images released and doc updated. Thanks @cv65kr

**Pull request merged**
