### PR TITLE
PHP 7.2 and 7.3 images fix/update

### PR DESCRIPTION
**Pull request by kowalk**

### CODE REVIEW

**Comment by kowalk** [comment]
@jorge07 affected with https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/pull/112/

**Comment by jorge07** [comment]
Great! I'll merge an create a release for this

**Comment by jorge07** [comment]
I need to improve the tests there're false positives

**Comment by jorge07** [comment]
docker exec php7.3 php -v
PHP 7.2.18 (cli) (built: May  4 2019 16:25:12) ( NTS )

**Comment by kowalk** [comment]
> docker exec php7.3 php -v
> PHP 7.2.18 (cli) (built: May 4 2019 16:25:12) ( NTS )

@jorge07 I've fixed that and added php version check to .travis.yml

**Comment by kowalk** [comment]
@jorge07 all checks are green now

**Comment by jorge07** [comment]
That's a really great job @kowalk

**Comment by jorge07** [comment]
I'm just created a release for:
- 5.6
- 5.6-dev
- 5.6.38
- 5.6.38-dev
- 7.1
- 7.1-dev
- 7.1.17
- 7.1.17-dev
- 7.2
- 7.2-dev
- 7.2.18
- 7.2.18-dev
- 7.3
- 7.3-dev
- 7.3.5
- 7.3.5-dev

**Pull request merged**
